### ISSUE TITLE
Case-sensitive path breaks live preview refresh

### ISSUE THREAD

**Issue by RaptorCZ** [jdiehl/brackets-less-autocompile#100]
I'm not sure if it is problem in Brackets or in Autocompile plugin. It depends, who is calling "refresh browser".

I have simple project:
[test.zip](https://github.com/jdiehl/brackets-less-autocompile/files/1263616/test.zip)

Changing LESS file is not reflected in Live preview. Background color changes in autocompiled css, but browser is not refreshed. It is because of CSS link in html file. It points to /**Styles**/styles.css, but folder is named "**styles**". Seems there is some problem with case sensitive texts.

**Comment by jdiehl** [comment]
This extension does not provide any live preview capabilities whatsoever.

**Comment by RaptorCZ** [comment]
Yes, I know, but I just want to find out if event about changed css file sends to Brackets this plugin or changes are maintained with Brackets itself.

**Comment by jdiehl** [comment]
Brackets. The extension only runs the less compiler which writes the file

**Comment by RaptorCZ** [comment]
Ok, then closing this.
