### ISSUE TITLE
compile.json output path

### ISSUE THREAD

**Issue by KazutoDE** [jdiehl/brackets-less-autocompile#101]
How do I set up an output path inside the JSON array?

The guide only explains how to add path to files but not how to set output paths.

**Comment by jdiehl** [comment]
This is not supported. You can use the // header to set a custom output.

**Comment by KazutoDE** [comment]
Which is not practicable if you have subfiles which should not be compiled. You can to add lines to every file instead of one global file to determine which files to compile and which not.
