### ISSUE TITLE
Error import .less

### ISSUE THREAD

**Issue by BloodyRed** [jdiehl/brackets-less-autocompile#102]
Hi,
I have a new error when I try to save my main.less, inside I @import "var.less" who is on the same folder, but I have this error : 
`Error in file '//server.io/var-www-html/website/public/css/less/main.less' on line 4: optional dependency 'request' required to import over http(s)`
Line 4 is my @import line.
I'm actually working on a distant server and his path is : \\server.io\var-www-html\website\
Before everything was working well, I restarted and unistall... But the error is still there.

**Comment by jdiehl** [comment]
This is a less error that I have no control over. Try running less manually and see if the same error occurs. If it does, try to consult the less project for help.
