### ISSUE TITLE
Automatic compiling doesn't work

### ISSUE THREAD

**Issue by fanart** [jdiehl/brackets-less-autocompile#56]
I installed the plug in a month ago, it worked totally fine. But recently it no longer work, I tried use "// out: .." with absolute path and relative path, neither works. I also created compile.json and it didn't work either. I have no idea how can fix the issue. Would you help me to fix that issue? Thanks!

**Comment by jdiehl** [comment]
Any update on this?

**Comment by 0x905EF** [comment]
Hey jdiel!

I had the same issue and found one error which caused this problem.. I included a class wrong. Hope I could help! Love your plugin.

Example:
```
.article-title-underline {
  article-title;
  border-bottom: 1.5px solid #ccc;
}
```

**Comment by jdiehl** [comment]
Are you sure you are using the latest version of the plugin? I just tested your example and see a valid error message:

    Error in file '/Users/jdiehl/Documents/Coding/brackets/Extensions/brackets-less-autocompile/example/a.less' on line 2: Unrecognised input

**Comment by mb-programmer** [comment]
hi
thanks for your good job on this extension
i also have this problem
LessAutoCompile doesn't work or it take too much time to work. some times it compile less file after around 15 minute
i work in Ubuntu 14.10 64bit and Brackets 1.1
i removed all other extensions and reinstalled Brackets but it didn't fixed

it is good to have a manual compile option :)

**Comment by jncs12** [comment]
Same problem here.
LessAutoCompile doesn't work. 
Windows 8.1 64 bits / Brackets 1.1
I already reinstalled Brackets. 
:-(

**Comment by jdiehl** [comment]
I need some more info to debug this... Please attach the files you are trying to compile and everything on the Brackets Console (accessible via Debug > Show Developer Tools)

**Comment by jncs12** [comment]
I decided to reinstall Brackets once again. It seems that reinstall is not enough... It is necessary to clean (delete) C:\Users\[user]\AppData\Roaming\Brackets.
I've done that and Less Autocompile is working! 
Thanks for your availability.

**Comment by mb-programmer** [comment]
thanks @jncs12 
i installed Bracket and also delete the config folder and thanks God every thing back to normal
this extension is really useful 
thanks to you @jdiehl

**Comment by quape** [comment]
Doesn't work here either. There is no output in the dev console when I save a .less file. Any hints?

**Comment by MrBodira** [comment]
Doesn't work here either. There is no creation of an compiled css file when I save a .less file. No errors in the dev console also. Do I mis something here?

**Comment by jdiehl** [comment]
Sorry, I cannot be of more assistance with these issues but I cannot reproduce this error on my machine. Please try all the steps suggested in the comments above. If the issues persists, you might also try posting to the brackets-dev mailing list and post your problems there.

**Comment by MrBodira** [comment]
I reinstalled Brackets and that did the trick now it works like a charm. Thanks.

**Comment by moi809** [comment]
I am getting the same error. Where same does nothing.
I opened the dev tool (chrome-devtools) and getting this error:
Uncaught TypeError: Cannot read property 'line' of undefined

**Comment by moi809** [comment]
I am getting the same error, where saving does nothing.
I opened the dev tool (chrome-devtools) and getting this error:
Uncaught TypeError: Cannot read property 'line' of undefined
source: /language/CodeInspection.js:423
