### ISSUE TITLE
less files do not compile

### ISSUE THREAD

**Issue by dumbwinter** [jdiehl/brackets-less-autocompile#57]
Hello,
I'm afraid the extension is not working at all for me, I'm on Windows 7 Pro 64 Italian version, Brackets v 1.1 (but it did't work on 1.0 either, not sure about the previous sprints).

test done: create a less file with a simple css directive -> save -> reopen and add a space -> save again -> check if a *.css file has been created -> facepalm
no errors or messages are raised (never seen one, even when it was working)
the file compiles correctly using koala.

thank you very much.

**Comment by jdiehl** [comment]
Closing this due to possible resolution and inactivity. If the problem persists, please reopen the issue and provide more details.

**Comment by dumbwinter** [comment]
I did a clean reinstall and it's working, I'll let you know if I find out which other extension is conflicting with yours.
thank you very much
