### ISSUE TITLE
Error in file 'undefined' on line undefined: undefined

### ISSUE THREAD

**Issue by ppoetsma** [jdiehl/brackets-less-autocompile#58]
Hi,

The "Error in file 'undefined' on line undefined: undefined" issue is back. I am using Brackets Release 1.1 build 1.1.0-15558 (release ea908cae5) and version 1.1.5 (latest) of your great extension. Whatever project I open, they all give this error withing a few seconds (no save required to trigger it). And these projects worked fine some weeks ago, probably late November was the last time I looked at them. In the mean time I updated Brackets and all extensions to their latest version with this error as result.

Do you have any clue what could be wrong?

Regards,
Paul

**Comment by jdiehl** [comment]
Thanks for the kind words and sorry to hear that you are having problems with the updated version. I will need some more info to get to the bottom of this...

* Can you try compiling your less files manually (please use the latest less compiler) and report any errors that occur?
* Also can you provide a minimum example of the less files that do not work?
* Finally, please check the Brackets console from the developer tools for any error messages related to the extension.

Cheers

**Comment by ppoetsma** [comment]
It is the first line which is causing the problem:
// out: gappless.css, compress: true, sourceMap: true, sourceMapFilename: gappless.map

When I remove the sourceMapFilename part it works fine, but it results in a map-file with the name gappless.css.map.

**Comment by jdiehl** [comment]
Thanks for the details. I found and eliminated the bug. Just update the extension. Cheers

**Comment by ppoetsma** [comment]
Works! Thanks for the quick solution.

**Comment by ondefar** [comment]
My first time on git, so move / add / delete if this falls out of normal behavior :)

I get the undefined error on latest build of brackets and your lovely plugin, but only when the file is opened from "open folder" in brackets.
If I browse to the file and edit, no errors occur..

This is what I get in the dev/console:
NodeSocketTransport - start
NodeDebugUtils.js:114 [node-error 9:47:06 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot call method 'toString' of undefined
    at C:\Users\userID\AppData\Roaming\Brackets\extensions\user\jdiehl.less-autocompile\node\LessCompiler.js:48:28
    at fs.js:207:20
    at OpenReq.Req.done (C:\Program Files (x86)\Brackets\www\extensibility\node\node_modules\fs-extra\node_modules\rimraf\node_modules\graceful-fs\graceful-fs.js:142:5)
    at OpenReq.done (C:\Program Files (x86)\Brackets\www\extensibility\node\node_modules\fs-extra\node_modules\rimraf\node_modules\graceful-fs\graceful-fs.js:64:22)
    at Object.oncomplete (fs.js:107:15)

...and some websocketconnection fail / network errors (?)

**Comment by jdiehl** [comment]
Thanks for the detail, will take a look at it

**Comment by jdiehl** [comment]
I added an error message that explains the problem. Just update the extension

**Comment by christraverse** [comment]
I think I'm getting this same problem, using the current build. AutoCompile is the only plugin I'm running, and my less files aren't compiling on save, but throwing up this error message.

'Uncaught TypeError: Cannot read property 'line' of undefine' on /language/CodeInspection.js:406

**Comment by jdiehl** [comment]
Did the solution from @ondefar fix your problem as well? Did you update the extension after my last comment?
