### ISSUE TITLE
console error when Brackets loads & when .less file is saved

### ISSUE THREAD

**Issue by teokosmo** [jdiehl/brackets-less-autocompile#59]
Hello,
I get the following error in Brackets (Release 1.1 build 1.1.0-15558) console
when using your plugin, version 1.1.7

![2015-01-14_175714](https://cloud.githubusercontent.com/assets/710862/5741965/5f16e646-9c17-11e4-805a-f84f0c29cd13.png)

**Comment by jdiehl** [comment]
The highlighted line (main.js:103) returns an error that occurred with either the node connection or loading the configuration files. You can set a breakpoint there and inspect the error variable for details. However, I fear the problem does not lie with the plugin but some other mechanism that is broken in your installation. Reinstalling Brackets might fix this...

**Comment by jncs12** [comment]
I also have this problem. I arlready reinstalled Brackets.

**Comment by jncs12** [comment]
I suggest a Brackets clean reinstall.
In Windows, delete C:\Users\[user]\AppData\Roaming\Brackets.

**Comment by teokosmo** [comment]
thanks for your suggestion but still no luck

**Comment by jdiehl** [comment]
Please attach the files you are trying to compile (all less-files and any compile.json / .brackets.json you are using)

**Comment by teokosmo** [comment]
I am conviced that there is a problem in my installation because i get other errors too, like:
Error watching project root:  T:/wwwroot/....
I work on Windows and the source code is in a remote server on which I have a map network drive
(T:)

My less file is really simple:

@bg_inv : #173070;

h1, h2, h3, h4, h5, h6, .h4 {
	color: @bg_inv;
}

Also my colleague who works on Ubuntu has no problem at all.

**Comment by jdiehl** [comment]
Did you try deleting the Brackets AppData folder?
Also, please try copying the files to a local disk and running Brackets less-auto-compile on that...

**Comment by teokosmo** [comment]
Did try both of them but still no luck. Thanks anyway for your suggestions.
