### ISSUE TITLE
Auto compiling is not working

### ISSUE THREAD

**Issue by siwwar** [jdiehl/brackets-less-autocompile#60]
The plugin is not working, I have added the compile options to the head of my .less file as following:
```
// out: ../style/style2.css, compress: true, strictMath: true
```
I did restart the Brackets after installing the plugin.
Did I missed something?

I am new to Brackets, I just installed it and added the LESS Autocompile plugin. I am using Brackets  release 1.1 build 1.1.0-15558 on Windows 7 64bit.

**Comment by n1kkou** [comment]
You can start by checking the file write permission

**Comment by siwwar** [comment]
Where to check exactly? Knowing that I am running Brackets as Administrator to avoid such issues.

**Comment by n1kkou** [comment]
try to set permissions for your project's root folder to 777 recursive, and see if your file is generated. To see if you have full rights on that folder, right click on it, go to "Security" tab, and click on the user you are authenticated with. You will see a checkbox for each operation type(read, write, execute, so on)

**Comment by siwwar** [comment]
Unfortunately, still not compiling, I would like to mention that i'm working on a local files.

Following are screenshots of security settings of my project folder

![snap01](https://cloud.githubusercontent.com/assets/1453816/5837223/589ab7f8-a18e-11e4-8e3f-26c368741862.png)

![snap02](https://cloud.githubusercontent.com/assets/1453816/5837346/7cb4e55e-a18f-11e4-8ec9-e7b3f8f0e468.png)

**Comment by n1kkou** [comment]
try to reinstall the extension, and if that wont fix the problem, reinstall brackets. It's hard to guess the problem, as long as you wont get any errors. This is only my suggestion :)

**Comment by jdiehl** [comment]
Sorry for the lack of error messages. You might want to check the Brackets console for any error messages before reinstalling brackets / the extension. You can open it by selecting "Open Developer Tools" from the menu. Also please try to run lessc manually and see whether it complains about anything.

**Comment by siwwar** [comment]
Sorry for any delay in my response. Thank you guys for your help and support.

The problem has been solved! It comes form the unavailability of internet connection, I am working behind a proxy server and I did not know that I can configure Brackets to work behind one. So, I was installing the plugins manually, until I have found some documentation of configuring a proxy server into Brackets, you can found it [here](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences).

After configuring the proxy server the plugin worked just fine.

Once again, thank you guys for your help and for this nice plugin.

Regards,

**Comment by jdiehl** [comment]
Glad to hear you were able to resolve the issue.

**Comment by iamdave210** [comment]
I'm having this issue, or a similar one, but I am able to install the plugin from the Extension Manager. Reinstalling has not help and I get no error messages in the dev console. It works with existing LESS files in the project but it will not create new ones. I tried creating the file manually but it does not overwrite it. I'm on Windows 7 and Brackets has no trouble saving or creating files in this same directory.

The first line of the file that **isn't** working looks like this:
`// out: ./ttu17.print.css, compress: true, strictMath: true`

The first line of the file that **is** working looks like this:
`// out: ./ttu17.css, compress: true, strictMath: true`

I have a .brackets.json file in my project that contains the following:
`{"less": ["ttu17.less"]}`

Am I doing something wrong?

**Comment by iamdave210** [comment]
It doesn't appear to be running at all on the new page. I put some syntax errors in the file and it saved with a green checkmark and no complaints.

**Comment by jdiehl** [comment]
Try removing the `./` from the output file.

**Comment by jdiehl** [comment]
Nevermind. The `brackets.json` file tells the extension to only ever compile ttu17.less. If you want to compile more than one file, add them to the list or remove `brackets.json`
