### ISSUE TITLE
less-autocompile has timed out

### ISSUE THREAD

**Issue by h2u** [jdiehl/brackets-less-autocompile#61]
less-autocompile has timed out after waiting for 10000 ms
brackets 1.2, windows 8.1

i see this error 50 times in a day :)

**Comment by jdiehl** [comment]
Sorry to hear that. Others have reported similar problems with Brackets and its node connection. Can you try deleting all local content AppData reinstalling Brackets as suggested in #59?

**Comment by h2u** [comment]
I alredy tried "clear" install. And yes, Node always die.
Less autocompile not the only who stops working. Ftp plugins die after some time too. Hate it... :)

**Comment by martinib77** [comment]
i'm having the same problem, brackets 1.2 on win7.
Also ocurring on Linux Mint.

**Comment by jdiehl** [comment]
Have you tried reporting this in the official Brackets forum? As it is concerned with the node connection, I am not sure it is the plugin that is causing the issue.
