### ISSUE TITLE
Notorious "Possibly missing something" of less-autocompile.

### ISSUE THREAD

**Issue by pogan** [jdiehl/brackets-less-autocompile#64]
Hi! 
Since i had to switch to sshfs I am getting always the same error on save:

```
Error in file '.../main.less' on line 185: Unrecognised input. Possibly missing something
```

The quick but irritating workaround is to wait a few seconds between saves, 
enough so the brackets for some reason notices you about "External Changes" and wheather you want to overwrite. If you do, autocompile works great and everything is fine, but without the overwrite it's always the same error, and it's always 4th or 5th line from the end of the file.
(the code is for sure ok, it happens on every less file)

My setup is, brackets sprint 2 build 1.2.0-15697 (release 8f82e2a97) , Windows 7x64 and win-sshfs.
node v0.12.0, npm 2.5.1, lessc 2.4.0

If it's of any help - less2css plugin for SublimeText2 also has this problem, seems like it's sshfs related...

**Comment by jdiehl** [comment]
I don't really know what to do here.. To fix the problem for yourself, you could try adding a `setTimeout` before triggering the less compile. However, I do not see how this could be solved in a generic matter, and I have not heard from anyone else having similar problems.
