### ISSUE TITLE
Not in the brackets extension manager

### ISSUE THREAD

**Issue by CodyL19** [jdiehl/brackets-less-autocompile#66]
I'm using the Linux version of brackets, and only see a LESS to HTML converter in the manager, no LESS Auto compile. I'd really like to try this out.

**Comment by jdiehl** [comment]
You can always install the extension manually by following this guide: https://github.com/adobe/brackets/wiki/Brackets-Extensions

**Comment by jdiehl** [comment]
Should be in there now.
