### ISSUE TITLE
Compilation feedback

### ISSUE THREAD

**Issue by Garito** [jdiehl/brackets-less-autocompile#67]
Hi!
Is there any way to get feedback from the compilation of the less files?

I'm using compile.json but when I save a less file the compilation only occurs if there are no errors but if there are no feedback is provided so you need to figure out by yourself

am I missing something?

Thanks!

**Comment by jdiehl** [comment]
You should get feedback in a panel below your editor. If that does not work, something is broken. Please try the steps suggested in #56.

**Comment by Garito** [comment]
Nice! I found it

Anything new about the timeout error?

**Comment by jdiehl** [comment]
I am not sure what you mean

**Comment by Garito** [comment]
I'm talking about:
https://github.com/jdiehl/brackets-less-autocompile/issues/61

**Comment by jdiehl** [comment]
I fear not. It think it might be a problem with the Brackets installation, though.

**Comment by Garito** [comment]
Ok, thanks!
