### ISSUE TITLE
Autoprefixer configuration

### ISSUE THREAD

**Issue by proengine** [jdiehl/brackets-less-autocompile#68]
I suggest to add a simple code update to support more parameters in autoprefixer option.
maybe somenthing like that:

```javascript
// autoprefixer
if (options.autoprefixer) {
  var autoprefixerOptions = {};
  if (typeof options.autoprefixer === 'string') {
    //autoprefixerOptions.browsers = [options.autoprefixer];
       autoprefixerOptions.browsers = options.autoprefixer.split(';');
  }
  options.plugins.push(new LessPluginAutoPrefix(autoprefixerOptions));
}
```

Regards.

**Comment by jdiehl** [comment]
Can you submit a pull request with the change?

**Comment by rzontar** [comment]
Would love to give this a try. Any reason why we are not seeing this feature in Brackets yet? The extensions still list the version 1.1.8.

**Comment by jdiehl** [comment]
I had problems with the brackets extension registry, which are resolved now. The update should be available soon.
