### ISSUE TITLE
Can I specify glob pattern auto-compiling?

### ISSUE THREAD

**Issue by kamrenz** [jdiehl/brackets-less-autocompile#70]
I have a folder that contains all my Less code. I want that whole folder to be watched. How is something like the following accomplished?
```
{ "less": [ "src/css/main.less", "src/css/less-component/*.less" ] }
```

**Comment by jdiehl** [comment]
This is not possible and does not make sense in my opinion for this extension. If you want to compile a number of less scripts, you should consider using gulp or grunt.
