### ISSUE TITLE
Set compiled files names my mask

### ISSUE THREAD

**Issue by thybzi** [jdiehl/brackets-less-autocompile#72]
I want to compile *any* LESS file that exist in one particular folder (and none of other LESS files not residing in this folder).

It would be great to have an option to set:
```
{
    "less": [ "resources/less/*.less" ]
}
```

instead of
```
{
    "less": [
        "resources/less/desktop.less",
        "resources/less/desktop_ie9.less",
        "resources/less/external_desktop.less",
        "resources/less/external_mobile.less",
        "resources/less/mobile.less",
        ... etc
    ]
}
```

This much shorter, more readable, and also more consistant (because if I rename or add some file in this folder, I sure need it to be compiled)

**Comment by jdiehl** [comment]
This was suggested in #70 and for the reasons mentioned there, I am reluctant of adding this.
