### ISSUE TITLE
An option to remove comment from the top of output CSS

### ISSUE THREAD

**Issue by thybzi** [jdiehl/brackets-less-autocompile#73]
How can I remove a comment on the top of my output CSS file?
```/* Generated by less 2.4.0 */```
System nodejs lessc doesn't output this by default, neither does PhpStorm watch (which is also using system lessc)

**Comment by jdiehl** [comment]
When compiling less files with the compress option // compress: true, the comment is removed. There is no other way of removing the comment, and I don't really see a reason why that would be necessary.
