### ISSUE TITLE
Set output file in .brackets.json

### ISSUE THREAD

**Issue by thybzi** [jdiehl/brackets-less-autocompile#74]
It would be great to set output CSS path in the same place of `.brackets.json`

```
{
    "less": {
        "resources/less/main.less": "htdocs/css/main.css"
    }
}
```

Or even (see #72):
```
{
    "less": {
        "resources/less/*.less": "htdocs/css/*.css"
    }
}
```

P.S. I know that the same can be achieved by setting that in file:
```
// out: ../dist/app.css
```
But I think that storing such things in per-project config is much better practice

P.P.S. Maybe adding "files" subkey inside "less" key is more convinient for developing this feature

**Comment by jdiehl** [comment]
Related to  #51
