### ISSUE TITLE
install extension with zip package

### ISSUE THREAD

**Issue by element303** [jdiehl/brackets-less-autocompile#76]
Hello,
can you complete the documentation to install extension with zip package ?
I found the good link to install zip package at https://brackets-registry.aboutweb.com/
(brackets install the zip master from github with no error ! but it doesn't work...)

**Comment by jdiehl** [comment]
Not quite sure what you mean and the provided link does not seem to work at the moment.

**Comment by element303** [comment]
the link comes from official documentation https://github.com/adobe/brackets/wiki/Brackets-Extensions

my network is restricted so i must use the manuel installation instructions : 
https://github.com/adobe/brackets/wiki/Brackets-Extensions#manual-installremoveupdate

in this case, the direct link in the documentation would be very useful (because the URL to a GitHub repo doesn't work, the extension needs some build/packaging)

**Comment by jdiehl** [comment]
I added a section to the readme
