### ISSUE TITLE
Not an issue, a suggestion

### ISSUE THREAD

**Issue by JeromeClerc** [jdiehl/brackets-less-autocompile#77]
I was trying to compile a LESS file where a variable was missing. My CSS dose not change at all, but no alert give me some infos to debug my LESS. It will be very comfortable and useful to have a feedback of compiling errors. Maybe there is already a way to have it, but I did not find how to do that. It will be nice if that feature could be add to your LESS autocompile.

**Comment by jdiehl** [comment]
This is already included :) After compiling an erroneous file, click on the yellow triangle in the status bar and a panel with the error description appears.

**Comment by JeromeClerc** [comment]
Ok. My bad, I did not try to click on the symbol at all. Thanks for your answer :)
