### ISSUE TITLE
I can't get the sourceMap to work

### ISSUE THREAD

**Issue by dessita** [jdiehl/brackets-less-autocompile#79]
tried sourceMap: true on top of my main less file but it does nothing. could you please provide example of how the syntax is supposed to be. Also as part of the compile.json. Thanks in advance!

**Comment by jdiehl** [comment]
```less
// sourceMap: true
a {
    color: red;
}
```
This example should generate two files: (1) a css file containing `/*# sourceMappingURL=???.css.map */`and a css.map file.

Currently, project-wide less settings are not supported via compile.json (you can only select the files to compile here -- see #51)
