### ISSUE TITLE
Will you update brackets-less-autocompile to newer version of less? 

### ISSUE THREAD

**Issue by tokkusu** [jdiehl/brackets-less-autocompile#82]
Current version is 2.6.0 : https://github.com/less/less.js

**Comment by jdiehl** [comment]
I tried updating the extension but the upload platform doesn't work at the moment. You can update your version of less manually by opening the `node` folder inside extension folder (`Library/Application Support/Brackets/extensions/user/brackets-less-autocompile` on a Mac) and installing the latest version of less by calling `npm i less`. Then, restart Brackets

**Comment by jdiehl** [comment]
It is now updated to less 3.10.3
