### ISSUE TITLE
Brakets :The extention don't work from las friday suddenly

### ISSUE THREAD

**Issue by verdepassion** [jdiehl/brackets-less-autocompile#83]
Hello
 from last Friday suddenly the less extension does not work; no message d'error.
I did the update thinking it was a procble of version but not
I uninstalled and install the extension 2 times

**Comment by jdiehl** [comment]
Please check the Brackets console for any errors (open Developer Tools from the View menu)

**Comment by verdepassion** [comment]
Hello : I hope it is this

![capture-compile](https://cloud.githubusercontent.com/assets/15109923/12744528/112e9af8-c995-11e5-85c2-179737b93b68.PNG)

**Comment by jdiehl** [comment]
It looks like an extension called brackets-ficompiler is causing trouble. Can you disable it and test brackets-less-autocompile again?

**Comment by verdepassion** [comment]
hello 
![capture-cosola](https://cloud.githubusercontent.com/assets/15109923/12943227/2313d624-cfe0-11e5-9f01-9c65e29ed165.PNG)
I continue to have errors on the console and does not compile less work.
I uninstall everything and installed

**Comment by verdepassion** [comment]
hello I continue to have errors on the console and does not compile less work.
I uninstall everything and installed

![capture-cosola](https://cloud.githubusercontent.com/assets/15109923/12943235/3a0437c0-cfe0-11e5-9b91-7dad81d24695.PNG)

**Comment by jdiehl** [comment]
There are still some warnings from `io.emmet...`, which I suspect might be the Emmet extension. Please try removing all extensions from the [extension folder](https://github.com/adobe/brackets/wiki/Extension-Locations) and reinstall Brackets. Then try installing the less-autocomplete extension [manually](https://github.com/adobe/brackets/wiki/Brackets-Extensions) (just check out this repository to the folder in the guide).

**Comment by guanzo** [comment]
I've reinstalled Brackets, this extension is the only one i have installed. I'm trying to combile a barebones less file, with an output location, one variable, and one css rule. I keep getting "Uncaught TypeError: Cannot read property 'line' of undefined" from "/language/CodeInspection.js:423". I've successfully compiled a less file from the cmd line. Not sure what else i can try.

**Comment by jdiehl** [comment]
@guanzo Please check the console for any errors as shown above
@verdepassion Did your problem resolve?
