### ISSUE TITLE
Project-wide compilation errors (variable is undefined)

### ISSUE THREAD

**Issue by ayatesca** [jdiehl/brackets-less-autocompile#85]
I have a project in which I am compiling multiple independent files specified in the compile.json. Some of them import the same base variables.less file for ease and consistency. However, in any child less file being imported that references a variable from the variables.less file it errors saying it is undefined.

Given the file structure:
variables.less
test1.less
--child.less
--child2.less
test2.less
--child3.less
--child4.less

And assuming each testX.less file imports their children as well as variables.less, any reference to a variable in variables.less will error stating it is undefined. However if I open the textX.less file and save it will compile fine.

I should also mention that if I remove either of the textX.less files from the compile.json compiling from the child files works fine.

I am running Windows 7 64-bit with the latest version of brackets and the extension.

**Comment by jdiehl** [comment]
Can you post your compile.json?

**Comment by ayatesca** [comment]
{ "less": [
	"/fend/less/fend_style.less", 
	"/fend/less/blog/blog.less", 
	"/fend/less/comersus/comersus.less", 
	"/fend/less/calendar/calendar.less", 
	"/fend/less/lightbox/lightbox.less",
	"/fend/less/sims/home.less";
]}

**Comment by jdiehl** [comment]
Were you able to fix the problem yourself or is this still an issue?

(I think the problem might lie in one of your referenced files in compile.json - you could try compiling them individually one by one and checking for errors)
