### ISSUE TITLE
Less-Autocompile errors

### ISSUE THREAD

**Issue by DaveTheGeek** [jdiehl/brackets-less-autocompile#88]
I keep getting the following error after using Brackets and Less-Autocompile for a few minutes.

`less-autocompile has timed out after waiting for 10000 ms	`

I've tried uninstalling and reinstalling the plugin, and also Brackets.

I'm running the following:
Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 13:58:11 GMT+0000

**Comment by jdiehl** [comment]
It looks like Brackets is having trouble launching the node process. To fix this, try reinstalling brackets without any plugins and the incrementally add plugins until things stop working.
