### ISSUE TITLE
// out: null is auto-compiling my files

### ISSUE THREAD

**Issue by jeffaustin81** [jdiehl/brackets-less-autocompile#89]
// out: null is not working. It's auto-compiling set to out: null. This only happens when the file is first created. I noticed once I add to some less in these files, delete the css files that originally got compiled then the problem goes away.

**Comment by jdiehl** [comment]
Not sure I understand your problem. `// out: null` is currently not supported (it should create a file call null)

**Comment by jeffaustin81** [comment]
It doesn't create a file called null. If I add a less file and open it, it
creates a css version. I added out: null to the top saved and deleted the
css file and it keeps creating the css file. But once I add content to the
less file and then delete the css version it works. It works just letting
you know. What do you use if you don't want a file auto-compiled?

**Comment by jdiehl** [comment]
The `compile.json` typically helps

**Comment by jeffaustin81** [comment]
Okay thanks
