### ISSUE TITLE
Don't work with "/" in imports ?

### ISSUE THREAD

**Issue by pit07** [jdiehl/brackets-less-autocompile#91]
Hi !
Thanks for this plugin !
But i have a problem : this plugin don't work when, in my main.less file, i have :

`@import "vendor/bootstrap.less`

in my .less. And i can't put all the Bootstrap less in the same repertory than my main.less....

Please help !
Thanks a lot !

**Comment by jdiehl** [comment]
The / should work. Note that on Windows you might have to use a \

I also noticed that you are missing a closing "

**Comment by pit07** [comment]
yes, ok for the closing ", wrong copy/paste ;)
But still not working with / or \. And i have no message error :(

**Comment by jdiehl** [comment]
Can you try compiling it manually with lessc?

Also can you take a look at the Brackets console (Developer Tools) and check for errors?

**Comment by pit07** [comment]
With console, i have :
>Error on line 2: 'vendor/bootstrap.less' wasn't found. 

strange, this file exists !

**Comment by jdiehl** [comment]
Could you attach a minimal not-working example as a zip archive to this issue? It should contain your folder structure and a few less files containing only their @import statements and maybe one or two actual rules to verify if it works

**Comment by pit07** [comment]
Hey !

It's ok... all is working ! It was my mystake...!
Thanks a lot for your time !

**Comment by jdiehl** [comment]
Np
