### ISSUE TITLE
Intermittent failure to compile

### ISSUE THREAD

**Issue by wahiche** [jdiehl/brackets-less-autocompile#93]
First let me say this plugin is the best less autocompile plugin.

I figured out that there is one piece that is missing, there is nothing that tells you of syntax errors that are stopping the compilation of the LESS file.

**Comment by jdiehl** [comment]
There used to be. My guess is the API changed... Will have a look!

**Comment by wahiche** [comment]
Cool, because that is a very important feature.  Again great work on the
plugin.

**Comment by mariojames** [comment]
I've been having problems with the LESS extension. It initially didn't work at all. I removed it, reinstalled it and it worked for a while. Then all of a sudden it stopped updating to an existing .css file. When I created a brand new file and saved it as .less nothing happened again. I completely removed and reinstalled Brackets. I noticed that the previous extensions that I had previously downloaded were already installed. Is that odd? Is there some kind of refresh function in Brackets? I'm going around in circles here. Thanks

**Comment by mariojames** [comment]
LESS won't auto-compile when errors are present! Thanking my classmate Tray for that one.

**Comment by 1xtr** [comment]
It's possible to update less from 2.5.1 to 3 ?
need calc()
in less: calc(50vw-570px);
in css: calc(-520vw);

**Comment by jdiehl** [comment]
I have updated the extension to less 3.10.3. Hopefully this will fix your problem

**Comment by jdiehl** [comment]
I have not done much lately with this project. Would yo
